---
title: "Adult2021DataSet"
author: "Lucille Bitzan"
date: '2022-10-25'
output: html_document
---

```{r}
library(tidyverse)
```


```{r}
nhisRevised<-adult21 %>% select(
HISPALLP_A,
RACEALLP_A,
DISAB3_A,
K6SPD_A,
AFNOW,
YRSINUS_A,
CITZNSTP_A,
PRTNREDUCP_A,
SPOUSEDUCP_A,
LEGMSTAT_A,
MARSTAT_A,
SASPPRACE_A,
SASPPHISP_A,
PRTNRAGETC_A,
SPOUSAGETC_A,
PRTNRWKFT_A,
PRTNRWRK_A,
SPOUSWKFT_A,
SPOUSWRK_A,
SPOUSESEX_A,
PRTNRSEX_A,
EMPWRKFT1_A,
EMPWRKLSW1_A,
EMPWKHRS3_A,
SMKECIGST_A,
SMKCIGST_A,
BMICAT_A,
WEIGHTLBTC_A,
HEIGHTTC_A,
PCNT18UPTC,
PCNTLT18TC,
LSATIS4R_A,
LSATIS11R_A,
COVER65_A,
COVER_A,
NOTCOV_A,
EDUCP_A,
MAXEDUCP_A,
PARSTAT_A,
PCNTADLT_A,
PCNTKIDS_A,
HISDETP_A,
HISP_A,
REGION,
SEX_A,
AGEP_A,
AGE65,
JOBSHIFT_A,
EMPWHYNOT_A,
NATUSBORN_A,
COMBAT_A,
AFVETTRN_A,
AFVET_A,
EVRMARRIED_A,
SPOUSEP_A,
SPOUSLIV_A,
MARITAL_A,
ORIENT_A,
SMOKELSCUR_A,
SMOKELSEV_A,
PIPECUR_A,
PIPEEV_A,
CIGAR30D_A,
CIGARCUR_A,
CIGAREV_A,
ECIGNOW_A,
ECIGEV_A,
CIG30D_A,
SMK30D_A,
CIGNOW_A,
SMKNOW_A,
SMKEV_A,
TSTSMHP_A,
WORTHLESS_A,
EFFORT_A,
HOPELESS_A,
RESTLESS_A,
NERVOUS_A,
SAD_A,
MHTHND_A,
MHTHDLY_A,
MHTPYNOW_A,
MHTHRPY_A,
MHRX_A,
DEPLEVEL_A,
DEPMED_A,
DEPFREQ_A,
ANXLEVEL_A,
ANXMED_A,
ANXFREQ_A,
PAYWORRY_A,
PAYNOBLLNW_A,
PAYBLL12M_A,
PREGNOW_A,
DEPEV_A,
ANXEV_A,
PHSTAT_A,
)
```

```{r}
#write.csv(nhisRevised,file="nhisRevised.cvs",col.names = TRUE)
```

